# Generated by Django 4.0.1 on 2022-01-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TweetsApi', '0002_comment_tweet_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=models.ImageField(default=None, upload_to='../media'),
        ),
    ]
